package dependencies

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNewDependencyResult_ComputesTotals(t *testing.T) {
	packages := []Package{
		{Name: "requests", Version: "2.28.0", PackageManager: "pip"},
		{Name: "flask", Version: "2.2.0", PackageManager: "pip"},
		{Name: "express", Version: "4.18.0", PackageManager: "npm"},
	}

	result := NewDependencyResult(packages, []string{"/project1"}, nil)

	if result.TotalPackages != 3 {
		t.Errorf("TotalPackages = %d, want 3", result.TotalPackages)
	}
	if result.Timestamp == "" {
		t.Error("Timestamp should not be empty")
	}
	if len(result.PackageManagersFound) != 2 {
		t.Errorf("PackageManagersFound length = %d, want 2", len(result.PackageManagersFound))
	}
	if result.Summary["pip"] != 2 {
		t.Errorf("Summary[pip] = %d, want 2", result.Summary["pip"])
	}
	if result.Summary["npm"] != 1 {
		t.Errorf("Summary[npm] = %d, want 1", result.Summary["npm"])
	}
}

func TestNewDependencyResult_GroupsByManager(t *testing.T) {
	packages := []Package{
		{Name: "a", Version: "1.0", PackageManager: "pip"},
		{Name: "b", Version: "2.0", PackageManager: "npm"},
		{Name: "c", Version: "3.0", PackageManager: "pip"},
	}

	result := NewDependencyResult(packages, nil, nil)

	if len(result.PackagesByManager["pip"]) != 2 {
		t.Errorf("PackagesByManager[pip] length = %d, want 2", len(result.PackagesByManager["pip"]))
	}
	if len(result.PackagesByManager["npm"]) != 1 {
		t.Errorf("PackagesByManager[npm] length = %d, want 1", len(result.PackagesByManager["npm"]))
	}
}

func TestNewDependencyResult_Empty(t *testing.T) {
	result := NewDependencyResult(nil, nil, []string{"err1"})
	if result.TotalPackages != 0 {
		t.Errorf("TotalPackages = %d, want 0", result.TotalPackages)
	}
	if len(result.Errors) != 1 {
		t.Errorf("Errors length = %d, want 1", len(result.Errors))
	}
}

func TestParseGoMod(t *testing.T) {
	tmpDir := t.TempDir()
	goModPath := filepath.Join(tmpDir, "go.mod")

	content := `module example.com/myproject

go 1.21

require (
	github.com/gin-gonic/gin v1.9.1
	github.com/stretchr/testify v1.8.4
)

require (
	github.com/indirect/dep v0.1.0 // indirect
)
`
	if err := os.WriteFile(goModPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	var packages []Package
	var scannedProjects []string
	seen := make(map[string]bool)
	addManager := func(string) {}

	parseGoMod(goModPath, &packages, &scannedProjects, seen, addManager)

	if len(packages) != 3 {
		t.Fatalf("packages length = %d, want 3", len(packages))
	}

	names := make(map[string]string)
	for _, p := range packages {
		names[p.Name] = p.Version
		if p.PackageManager != "go" {
			t.Errorf("PackageManager = %q, want %q", p.PackageManager, "go")
		}
		if p.InstallType != "project" {
			t.Errorf("InstallType = %q, want %q", p.InstallType, "project")
		}
	}
	if names["github.com/gin-gonic/gin"] != "v1.9.1" {
		t.Errorf("gin version = %q, want v1.9.1", names["github.com/gin-gonic/gin"])
	}
}

func TestParseCargoLock(t *testing.T) {
	tmpDir := t.TempDir()
	cargoLockPath := filepath.Join(tmpDir, "Cargo.lock")

	content := `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.180"

[[package]]
name = "tokio"
version = "1.29.1"
`
	if err := os.WriteFile(cargoLockPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	var packages []Package
	var scannedProjects []string
	seen := make(map[string]bool)
	addManager := func(string) {}

	parseCargoLock(cargoLockPath, &packages, &scannedProjects, seen, addManager)

	if len(packages) != 2 {
		t.Fatalf("packages length = %d, want 2", len(packages))
	}

	names := make(map[string]string)
	for _, p := range packages {
		names[p.Name] = p.Version
		if p.PackageManager != "cargo" {
			t.Errorf("PackageManager = %q, want %q", p.PackageManager, "cargo")
		}
	}
	if names["serde"] != "1.0.180" {
		t.Errorf("serde version = %q, want 1.0.180", names["serde"])
	}
	if names["tokio"] != "1.29.1" {
		t.Errorf("tokio version = %q, want 1.29.1", names["tokio"])
	}
}

func TestParseGemfileLock(t *testing.T) {
	tmpDir := t.TempDir()
	gemfilePath := filepath.Join(tmpDir, "Gemfile.lock")

	content := `GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.6)
    rails (7.0.6)

PLATFORMS
  ruby

BUNDLED WITH
   2.4.10
`
	if err := os.WriteFile(gemfilePath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	var packages []Package
	var scannedProjects []string
	seen := make(map[string]bool)
	addManager := func(string) {}

	parseGemfileLock(gemfilePath, &packages, &scannedProjects, seen, addManager)

	if len(packages) != 2 {
		t.Fatalf("packages length = %d, want 2", len(packages))
	}

	names := make(map[string]string)
	for _, p := range packages {
		names[p.Name] = p.Version
		if p.PackageManager != "gem" {
			t.Errorf("PackageManager = %q, want %q", p.PackageManager, "gem")
		}
	}
	if names["actioncable"] != "7.0.6" {
		t.Errorf("actioncable version = %q, want 7.0.6", names["actioncable"])
	}
	if names["rails"] != "7.0.6" {
		t.Errorf("rails version = %q, want 7.0.6", names["rails"])
	}
}

func TestParsePackageJSON(t *testing.T) {
	tmpDir := t.TempDir()
	pkgJSONPath := filepath.Join(tmpDir, "package.json")

	content := `{
  "name": "myapp",
  "dependencies": {
    "express": "^4.18.0",
    "lodash": "^4.17.21"
  },
  "devDependencies": {
    "jest": "^29.0.0"
  }
}`
	if err := os.WriteFile(pkgJSONPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	var packages []Package
	var scannedProjects []string
	seen := make(map[string]bool)
	addManager := func(string) {}

	parsePackageJSON(pkgJSONPath, &packages, &scannedProjects, seen, addManager)

	if len(packages) != 3 {
		t.Fatalf("packages length = %d, want 3", len(packages))
	}

	names := make(map[string]string)
	for _, p := range packages {
		names[p.Name] = p.Version
		if p.PackageManager != "npm" {
			t.Errorf("PackageManager = %q, want %q", p.PackageManager, "npm")
		}
		if p.InstallType != "project" {
			t.Errorf("InstallType = %q, want %q", p.InstallType, "project")
		}
	}
	if names["express"] != "^4.18.0" {
		t.Errorf("express version = %q, want ^4.18.0", names["express"])
	}
	if names["jest"] != "^29.0.0" {
		t.Errorf("jest version = %q, want ^29.0.0", names["jest"])
	}
}

func TestParseRequirementsTxt(t *testing.T) {
	tmpDir := t.TempDir()
	reqPath := filepath.Join(tmpDir, "requirements.txt")

	content := `# Python dependencies
requests==2.28.0
flask>=2.2.0
pytest
-e git+https://github.com/example/repo.git#egg=example
`
	if err := os.WriteFile(reqPath, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	var packages []Package
	var scannedProjects []string
	seen := make(map[string]bool)
	addManager := func(string) {}

	parseRequirementsTxt(reqPath, &packages, &scannedProjects, seen, addManager)

	if len(packages) != 3 {
		t.Fatalf("packages length = %d, want 3 (requests, flask, pytest)", len(packages))
	}

	names := make(map[string]string)
	for _, p := range packages {
		names[p.Name] = p.Version
	}
	if names["requests"] != "2.28.0" {
		t.Errorf("requests version = %q, want 2.28.0", names["requests"])
	}
	if names["pytest"] != "any" {
		t.Errorf("pytest version = %q, want any", names["pytest"])
	}
}
