"""baseline: PostgreSQL-native schema with enforced integrity

Replaces the previous 14 revisions with a single baseline generated from
models.py. The old chain had accumulated SQLite-shaped workarounds — five of its
revisions used batch_alter_table, 24 times in the initial schema alone — and
carried almost no integrity guarantees: no CHECK constraints, no database-side
defaults, and exactly one of 34 foreign keys with an explicit ON DELETE action.

Squashing was only possible because there was no data to preserve and no
external installation to support. Everything the old chain expressed is here,
plus:

  * ON DELETE on all 34 foreign keys — CASCADE for ownership, SET NULL for
    attribution (so audit entries and vulnerability findings outlive the rows
    they reference), RESTRICT on customer_keys.user_id. Parent deletion now
    cascades instead of failing: "Delete host" and "Delete customer key" had
    both been broken, since SQLAlchemy tried to NULL NOT NULL child columns.
  * CHECK constraints generated from the VALID_* vocabularies in models.py,
    which until now were advisory Python constants the database ignored.
  * timestamptz throughout, with server_default so an INSERT that bypasses the
    ORM cannot write a NULL created_at.
  * JSONB rather than json, and BigInteger identities on the append-only tables.
  * Composite (customer_key_id, host_id) foreign keys, making a cross-tenant row
    impossible to insert rather than one forgotten JOIN away.
  * Uniqueness on the scan-child tables, with NULLS NOT DISTINCT where the key
    includes nullable columns, so rescan ingestion is genuinely idempotent.
  * A trigger enforcing that audit_logs is append-only, which its docstring has
    always claimed but nothing checked.

Revision ID: 0001_baseline
Revises: None

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('publisher_display_name', sa.String(length=200), nullable=True),
    sa.Column('install_count', sa.BigInteger(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_unpublished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('unpublished_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_fetch_status', sa.Integer(), nullable=True),
    sa.CheckConstraint('average_rating IS NULL OR (average_rating >= 0 AND average_rating <= 5)', name='ck_ext_meta_rating'),
    sa.CheckConstraint('install_count IS NULL OR (install_count >= 0)', name='ck_ext_meta_install_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'extension_id', 'version', name='uq_ext_meta')
    )
    with op.batch_alter_table('extension_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_ext_meta_fetched_at', ['fetched_at'], unique=False)
        batch_op.create_index('idx_ext_meta_lookup', ['marketplace', 'extension_id', 'version'], unique=False)
        batch_op.create_index('idx_ext_meta_unpublished', ['is_unpublished'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='admin', nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.CheckConstraint("role IS NULL OR role IN ('admin', 'analyst', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('customer_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_keys_key'), ['key'], unique=True)

    op.create_table('expected_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source IS NULL OR source IN ('manual', 'mdm', 'scim')", name='ck_expected_hosts_source'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_key_id', 'hostname', name='uq_expected_key_host')
    )
    op.create_table('extension_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('match_publisher', sa.String(length=200), nullable=True),
    sa.Column('match_extension_id', sa.String(length=200), nullable=True),
    sa.Column('match_permission_glob', sa.String(length=200), nullable=True),
    sa.Column('match_risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("action IS NULL OR action IN ('allow', 'warn', 'block-alert', 'quarantine')", name='ck_extension_policies_action'),
    sa.CheckConstraint("match_risk_level IS NULL OR match_risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_extension_policies_risk_level'),
    sa.CheckConstraint('priority IS NULL OR (priority >= 0)', name='ck_extension_policies_priority'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_policies', schema=None) as batch_op:
        batch_op.create_index('idx_policy_customer_active', ['customer_key_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_policies_customer_key_id'), ['customer_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_policies_public_id'), ['public_id'], unique=True)

    op.create_table('extension_prevalence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('host_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prev_host_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_risk_level', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("max_risk_level IS NULL OR max_risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_prevalence_risk_level'),
    sa.CheckConstraint('host_count IS NULL OR (host_count >= 0)', name='ck_prevalence_host_count'),
    sa.CheckConstraint('prev_host_count IS NULL OR (prev_host_count >= 0)', name='ck_prevalence_prev_host_count'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_key_id', 'extension_id', name='uq_prevalence_key_ext')
    )
    with op.batch_alter_table('extension_prevalence', schema=None) as batch_op:
        batch_op.create_index('idx_prevalence_key', ['customer_key_id'], unique=False)

    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daemon_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('last_realtime_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_alarm_state', sa.String(length=16), server_default='ok', nullable=False),
    sa.Column('silent_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level_composite', sa.String(length=16), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("heartbeat_alarm_state IS NULL OR heartbeat_alarm_state IN ('ok', 'silent')", name='ck_hosts_heartbeat_state'),
    sa.CheckConstraint("risk_level_composite IS NULL OR risk_level_composite IN ('low', 'medium', 'high', 'critical')", name='ck_hosts_risk_level'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_hosts_risk_score'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_key_id', 'id', name='uq_hosts_tenant_id'),
    sa.UniqueConstraint('hostname', 'customer_key_id', name='unique_host_per_key')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_hosts_token_hash'), ['token_hash'], unique=False)

    op.create_table('remediation_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_event', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), server_default='notify_only', nullable=False),
    sa.Column('mode', sa.String(length=20), server_default='dry_run', nullable=False),
    sa.Column('min_severity', sa.String(length=20), server_default='high', nullable=True),
    sa.Column('max_actions_per_hour', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("action IS NULL OR action IN ('auto_quarantine', 'notify_only')", name='ck_playbooks_action'),
    sa.CheckConstraint("min_severity IS NULL OR min_severity IN ('low', 'medium', 'high', 'critical')", name='ck_playbooks_min_severity'),
    sa.CheckConstraint("mode IS NULL OR mode IN ('dry_run', 'active')", name='ck_playbooks_mode'),
    sa.CheckConstraint("trigger_event IS NULL OR trigger_event IN ('extension.threat_matched', 'policy.violation')", name='ck_playbooks_trigger'),
    sa.CheckConstraint('max_actions_per_hour IS NULL OR (max_actions_per_hour >= 1)', name='ck_playbooks_rate_limit'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_playbooks_public_id'), ['public_id'], unique=True)

    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='generic', nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IS NULL OR type IN ('generic', 'slack', 'pagerduty')", name='ck_webhook_subscriptions_type'),
    sa.CheckConstraint('consecutive_failures IS NULL OR (consecutive_failures >= 0)', name='ck_webhook_subscriptions_failures'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_customer_key_id'), ['customer_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_public_id'), ['public_id'], unique=True)

    op.create_table('hook_bypasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.String(length=500), nullable=True),
    sa.Column('commit_author', sa.String(length=200), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_hook_bypasses_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hook_bypasses', schema=None) as batch_op:
        batch_op.create_index('idx_hook_bypass_host', ['host_id', 'is_acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_hook_bypasses_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('policy_violations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('extension_name', sa.String(length=200), nullable=True),
    sa.Column('extension_version', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('action_taken', sa.String(length=20), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("action_taken IS NULL OR action_taken IN ('allow', 'warn', 'block-alert', 'quarantine')", name='ck_policy_violations_action'),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_policy_violations_risk_level'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_policy_violations_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['extension_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'policy_id', 'extension_id', 'extension_version', name='uq_policy_violation_per_ext_version', postgresql_nulls_not_distinct=True)
    )
    with op.batch_alter_table('policy_violations', schema=None) as batch_op:
        batch_op.create_index('idx_violation_host_resolved', ['host_id', 'is_resolved'], unique=False)
        batch_op.create_index('idx_violation_policy', ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_violations_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('scan_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_ides', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_extensions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('dangerous_extensions', sa.Integer(), server_default='0', nullable=True),
    sa.CheckConstraint('dangerous_extensions IS NULL OR (dangerous_extensions >= 0)', name='ck_scan_reports_dangerous'),
    sa.CheckConstraint('total_extensions IS NULL OR (total_extensions >= 0)', name='ck_scan_reports_total_extensions'),
    sa.CheckConstraint('total_ides IS NULL OR (total_ides >= 0)', name='ck_scan_reports_total_ides'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_scan_reports_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_reports_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('scan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IS NULL OR status IN ('pending', 'connecting', 'scanning_ides', 'scanning_secrets', 'scanning_packages', 'completed', 'failed', 'timeout')", name='ck_scan_requests_status'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_scan_requests_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_requests', schema=None) as batch_op:
        batch_op.create_index('idx_scan_request_status', ['host_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_requests_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('tamper_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='critical', nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('critical', 'high', 'medium')", name='ck_tamper_alerts_severity'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_tamper_alerts_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tamper_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_tamper_host', ['host_id', 'is_acknowledged'], unique=False)
        batch_op.create_index('idx_tamper_type', ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tamper_alerts_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IS NULL OR status IN ('pending', 'retrying', 'succeeded', 'failed')", name='ck_webhook_deliveries_status'),
    sa.CheckConstraint('attempt_count IS NULL OR (attempt_count >= 0)', name='ck_webhook_deliveries_attempts'),
    sa.CheckConstraint('response_code IS NULL OR (response_code >= 100 AND response_code <= 599)', name='ck_webhook_deliveries_response_code'),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index('idx_delivery_sub_status', ['subscription_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('ai_tool_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('is_running', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('config_path', sa.String(length=500), nullable=True),
    sa.Column('mcp_servers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redacted_secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_ai_tool_info_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'tool_name', name='uq_aitool_per_host_tool')
    )
    with op.batch_alter_table('ai_tool_info', schema=None) as batch_op:
        batch_op.create_index('idx_aitool_host', ['host_id', 'tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tool_info_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('enforcement_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=20), server_default='quarantine', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('extension_name', sa.String(length=200), nullable=True),
    sa.Column('extension_version', sa.String(length=50), nullable=True),
    sa.Column('ide_type', sa.String(length=50), nullable=True),
    sa.Column('original_path', sa.String(length=1000), nullable=True),
    sa.Column('quarantine_path', sa.String(length=1000), nullable=True),
    sa.Column('result_detail', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action IS NULL OR action IN ('quarantine', 'restore')", name='ck_enforcement_actions_action'),
    sa.CheckConstraint("status IS NULL OR status IN ('pending', 'dispatched', 'applied', 'failed', 'reverted')", name='ck_enforcement_actions_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_enforcement_actions_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_id'], ['policy_violations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enforcement_actions', schema=None) as batch_op:
        batch_op.create_index('idx_enforcement_host_status', ['host_id', 'status'], unique=False)
        batch_op.create_index('idx_enforcement_violation', ['violation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enforcement_actions_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('extension_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.BigInteger(), nullable=False),
    sa.Column('ide_name', sa.String(length=100), nullable=False),
    sa.Column('ide_version', sa.String(length=50), nullable=True),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('extension_name', sa.String(length=200), nullable=False),
    sa.Column('extension_version', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('maintainer', sa.String(length=200), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_extension_info_risk_level'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_extension_info_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'ide_name', 'extension_id', name='uq_extension_per_host_ide')
    )
    with op.batch_alter_table('extension_info', schema=None) as batch_op:
        batch_op.create_index('idx_extension_host', ['host_id', 'ide_name'], unique=False)
        batch_op.create_index('idx_extension_risk', ['risk_level', 'is_dangerous'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_info_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('package_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=False),
    sa.Column('install_type', sa.String(length=20), server_default='project', nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=True),
    sa.Column('lifecycle_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=20), server_default='project', nullable=True),
    sa.Column('source_extension', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("install_type IS NULL OR install_type IN ('global', 'project')", name='ck_package_info_install_type'),
    sa.CheckConstraint("source_type IS NULL OR source_type IN ('project', 'global', 'extension')", name='ck_package_info_source_type'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_package_info_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'package_manager', 'name', 'version', 'source_type', name='uq_package_per_host', postgresql_nulls_not_distinct=True)
    )
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.create_index('idx_package_host', ['host_id', 'package_manager'], unique=False)
        batch_op.create_index('idx_package_manager', ['package_manager'], unique=False)
        batch_op.create_index('idx_package_name', ['name'], unique=False)
        batch_op.create_index('idx_package_source', ['host_id', 'source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_info_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('secret_findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('secret_type', sa.String(length=50), nullable=False),
    sa.Column('variable_name', sa.String(length=200), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='critical', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('redacted_value', sa.String(length=200), server_default='', nullable=True),
    sa.Column('source', sa.String(length=20), server_default='filesystem', nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_author', sa.String(length=200), nullable=True),
    sa.Column('commit_date', sa.String(length=30), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical')", name='ck_secret_findings_severity'),
    sa.CheckConstraint("source IS NULL OR source IN ('filesystem', 'git_history')", name='ck_secret_findings_source'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_secret_findings_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'file_path', 'secret_type', 'variable_name', 'commit_hash', name='uq_secret_per_host_location', postgresql_nulls_not_distinct=True)
    )
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.create_index('idx_secret_host', ['host_id', 'is_resolved'], unique=False)
        batch_op.create_index('idx_secret_type', ['secret_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_findings_customer_key_id'), ['customer_key_id'], unique=False)

    op.create_table('vulnerabilities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('package_info_id', sa.BigInteger(), nullable=True),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('package_version', sa.String(length=100), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('vuln_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity_label', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_versions', sa.Text(), nullable=True),
    sa.Column('fixed_version', sa.String(length=100), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='osv.dev', nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.CheckConstraint("severity_label IS NULL OR severity_label IN ('low', 'medium', 'high', 'critical')", name='ck_vulnerabilities_severity'),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name='ck_vulnerabilities_cvss'),
    sa.ForeignKeyConstraint(['customer_key_id', 'host_id'], ['hosts.customer_key_id', 'hosts.id'], name='fk_vulnerabilities_host_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_info_id'], ['package_info.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'package_manager', 'package_name', 'package_version', 'vuln_id', name='uq_vuln_per_host_package', postgresql_nulls_not_distinct=True)
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index('idx_vuln_host_resolved', ['host_id', 'is_resolved'], unique=False)
        batch_op.create_index('idx_vuln_id', ['vuln_id'], unique=False)
        batch_op.create_index('idx_vuln_package', ['package_name', 'package_manager'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_customer_key_id'), ['customer_key_id'], unique=False)

    # ── audit_logs is append-only ───────────────────────────────────
    # The model docstring has always promised this, but the table was ordinary:
    # any code path, or anyone with a psql prompt, could rewrite the record of
    # who did what. A trigger turns that promise into an enforced property.
    op.execute("""
        CREATE FUNCTION ideviewer_audit_logs_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs is append-only; % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION ideviewer_audit_logs_append_only();
    """)

    # ── updated_at maintenance ──────────────────────────────────────
    op.execute("""
        CREATE FUNCTION ideviewer_touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER extension_prevalence_touch_updated_at
        BEFORE UPDATE ON extension_prevalence
        FOR EACH ROW EXECUTE FUNCTION ideviewer_touch_updated_at();
    """)
    # ### end Alembic commands ###
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS extension_prevalence_touch_updated_at ON extension_prevalence")
    op.execute("DROP FUNCTION IF EXISTS ideviewer_touch_updated_at()")
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS ideviewer_audit_logs_append_only()")
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_customer_key_id'))
        batch_op.drop_index('idx_vuln_package')
        batch_op.drop_index('idx_vuln_id')
        batch_op.drop_index('idx_vuln_host_resolved')

    op.drop_table('vulnerabilities')
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_findings_customer_key_id'))
        batch_op.drop_index('idx_secret_type')
        batch_op.drop_index('idx_secret_host')

    op.drop_table('secret_findings')
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_info_customer_key_id'))
        batch_op.drop_index('idx_package_source')
        batch_op.drop_index('idx_package_name')
        batch_op.drop_index('idx_package_manager')
        batch_op.drop_index('idx_package_host')

    op.drop_table('package_info')
    with op.batch_alter_table('extension_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_info_customer_key_id'))
        batch_op.drop_index('idx_extension_risk')
        batch_op.drop_index('idx_extension_host')

    op.drop_table('extension_info')
    with op.batch_alter_table('enforcement_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enforcement_actions_customer_key_id'))
        batch_op.drop_index('idx_enforcement_violation')
        batch_op.drop_index('idx_enforcement_host_status')

    op.drop_table('enforcement_actions')
    with op.batch_alter_table('ai_tool_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tool_info_customer_key_id'))
        batch_op.drop_index('idx_aitool_host')

    op.drop_table('ai_tool_info')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_created_at'))
        batch_op.drop_index('idx_delivery_sub_status')

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('tamper_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tamper_alerts_customer_key_id'))
        batch_op.drop_index('idx_tamper_type')
        batch_op.drop_index('idx_tamper_host')

    op.drop_table('tamper_alerts')
    with op.batch_alter_table('scan_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_requests_customer_key_id'))
        batch_op.drop_index('idx_scan_request_status')

    op.drop_table('scan_requests')
    with op.batch_alter_table('scan_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_reports_customer_key_id'))
        batch_op.drop_index(batch_op.f('ix_scan_reports_created_at'))

    op.drop_table('scan_reports')
    with op.batch_alter_table('policy_violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_violations_customer_key_id'))
        batch_op.drop_index('idx_violation_policy')
        batch_op.drop_index('idx_violation_host_resolved')

    op.drop_table('policy_violations')
    with op.batch_alter_table('hook_bypasses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hook_bypasses_customer_key_id'))
        batch_op.drop_index('idx_hook_bypass_host')

    op.drop_table('hook_bypasses')
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_public_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_customer_key_id'))

    op.drop_table('webhook_subscriptions')
    with op.batch_alter_table('remediation_playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_playbooks_public_id'))

    op.drop_table('remediation_playbooks')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_token_hash'))
        batch_op.drop_index(batch_op.f('ix_hosts_public_id'))

    op.drop_table('hosts')
    with op.batch_alter_table('extension_prevalence', schema=None) as batch_op:
        batch_op.drop_index('idx_prevalence_key')

    op.drop_table('extension_prevalence')
    with op.batch_alter_table('extension_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_policies_public_id'))
        batch_op.drop_index(batch_op.f('ix_extension_policies_customer_key_id'))
        batch_op.drop_index('idx_policy_customer_active')

    op.drop_table('extension_policies')
    op.drop_table('expected_hosts')
    with op.batch_alter_table('customer_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_keys_key'))

    op.drop_table('customer_keys')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('extension_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_ext_meta_unpublished')
        batch_op.drop_index('idx_ext_meta_lookup')
        batch_op.drop_index('idx_ext_meta_fetched_at')

    op.drop_table('extension_metadata')
    # ### end Alembic commands ###
