"""Initial schema

Revision ID: 3b55959a4b71
Revises: 
Create Date: 2026-04-03 12:53:08.147027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b55959a4b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('customer_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_hosts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_keys_key'), ['key'], unique=True)

    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('customer_key_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('daemon_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_realtime_event', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_key_id'], ['customer_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'customer_key_id', name='unique_host_per_key')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_public_id'), ['public_id'], unique=True)

    op.create_table('hook_bypasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.String(length=500), nullable=True),
    sa.Column('commit_author', sa.String(length=200), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hook_bypasses', schema=None) as batch_op:
        batch_op.create_index('idx_hook_bypass_host', ['host_id', 'is_acknowledged'], unique=False)

    op.create_table('scan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scan_data', sa.JSON(), nullable=False),
    sa.Column('total_ides', sa.Integer(), nullable=True),
    sa.Column('total_extensions', sa.Integer(), nullable=True),
    sa.Column('dangerous_extensions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_reports_created_at'), ['created_at'], unique=False)

    op.create_table('scan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('log_entries', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_requests', schema=None) as batch_op:
        batch_op.create_index('idx_scan_request_status', ['host_id', 'status'], unique=False)

    op.create_table('tamper_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tamper_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_tamper_host', ['host_id', 'is_acknowledged'], unique=False)
        batch_op.create_index('idx_tamper_type', ['alert_type'], unique=False)

    op.create_table('ai_tool_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('config_path', sa.String(length=500), nullable=True),
    sa.Column('mcp_servers', sa.JSON(), nullable=True),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('redacted_secrets', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tool_info', schema=None) as batch_op:
        batch_op.create_index('idx_aitool_host', ['host_id', 'tool_name'], unique=False)

    op.create_table('extension_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.Integer(), nullable=False),
    sa.Column('ide_name', sa.String(length=100), nullable=False),
    sa.Column('ide_version', sa.String(length=50), nullable=True),
    sa.Column('extension_id', sa.String(length=200), nullable=False),
    sa.Column('extension_name', sa.String(length=200), nullable=False),
    sa.Column('extension_version', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('maintainer', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_info', schema=None) as batch_op:
        batch_op.create_index('idx_extension_host', ['host_id', 'ide_name'], unique=False)
        batch_op.create_index('idx_extension_risk', ['risk_level', 'is_dangerous'], unique=False)

    op.create_table('package_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=False),
    sa.Column('install_type', sa.String(length=20), nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=True),
    sa.Column('lifecycle_hooks', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_extension', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.create_index('idx_package_host', ['host_id', 'package_manager'], unique=False)
        batch_op.create_index('idx_package_manager', ['package_manager'], unique=False)
        batch_op.create_index('idx_package_name', ['name'], unique=False)
        batch_op.create_index('idx_package_source', ['host_id', 'source_type'], unique=False)

    op.create_table('secret_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scan_report_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('secret_type', sa.String(length=50), nullable=False),
    sa.Column('variable_name', sa.String(length=200), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('redacted_value', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_author', sa.String(length=200), nullable=True),
    sa.Column('commit_date', sa.String(length=30), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.create_index('idx_secret_host', ['host_id', 'is_resolved'], unique=False)
        batch_op.create_index('idx_secret_type', ['secret_type'], unique=False)

    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('package_info_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('package_version', sa.String(length=100), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('vuln_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('severity_label', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_versions', sa.Text(), nullable=True),
    sa.Column('fixed_version', sa.String(length=100), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['package_info_id'], ['package_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index('idx_vuln_host_resolved', ['host_id', 'is_resolved'], unique=False)
        batch_op.create_index('idx_vuln_id', ['vuln_id'], unique=False)
        batch_op.create_index('idx_vuln_package', ['package_name', 'package_manager'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index('idx_vuln_package')
        batch_op.drop_index('idx_vuln_id')
        batch_op.drop_index('idx_vuln_host_resolved')

    op.drop_table('vulnerabilities')
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.drop_index('idx_secret_type')
        batch_op.drop_index('idx_secret_host')

    op.drop_table('secret_findings')
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.drop_index('idx_package_source')
        batch_op.drop_index('idx_package_name')
        batch_op.drop_index('idx_package_manager')
        batch_op.drop_index('idx_package_host')

    op.drop_table('package_info')
    with op.batch_alter_table('extension_info', schema=None) as batch_op:
        batch_op.drop_index('idx_extension_risk')
        batch_op.drop_index('idx_extension_host')

    op.drop_table('extension_info')
    with op.batch_alter_table('ai_tool_info', schema=None) as batch_op:
        batch_op.drop_index('idx_aitool_host')

    op.drop_table('ai_tool_info')
    with op.batch_alter_table('tamper_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_tamper_type')
        batch_op.drop_index('idx_tamper_host')

    op.drop_table('tamper_alerts')
    with op.batch_alter_table('scan_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_request_status')

    op.drop_table('scan_requests')
    with op.batch_alter_table('scan_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_reports_created_at'))

    op.drop_table('scan_reports')
    with op.batch_alter_table('hook_bypasses', schema=None) as batch_op:
        batch_op.drop_index('idx_hook_bypass_host')

    op.drop_table('hook_bypasses')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_public_id'))

    op.drop_table('hosts')
    with op.batch_alter_table('customer_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_keys_key'))

    op.drop_table('customer_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
